# Generated by Django 3.0.8 on 2020-07-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_description', models.TextField()),
            ],
        ),
    ]
